version: 0.2

env:
  parameter-store:
    DD_API_KEY: "DD_API_KEY"

phases:
  pre_build:
    commands:
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $ACCOUNT_ID.dkr.ecr.ap-northeast-1.amazonaws.com
      - REPOSITORY_URI=$ACCOUNT_ID.dkr.ecr.ap-northeast-1.amazonaws.com/keirin-bet-$ENV-ecr-money
      - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - if [ -z "$IMAGE_TAG" ]; then IMAGE_TAG="latest"; fi # デフォルト値を設定

  build:
    commands:
      - echo "Building the Docker image..."
      - ls -l
      - docker build -t $REPOSITORY_URI:latest -f docker/Dockerfile .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG

  post_build:
    commands:
      - echo "Pushing the Docker image..."
      - docker push $REPOSITORY_URI:latest || echo "Docker push failed"
      - docker push $REPOSITORY_URI:$IMAGE_TAG || echo "Docker push with tag failed"
      - printf '{"Version":"1.0","ImageURI":"%s"}' $REPOSITORY_URI:$IMAGE_TAG > imageDetail.json
      - sed -i -e "s#<ENV>#$ENV#" cicd/appspec.yml
      - sed -i -e "s#<ENV>#$ENV#" cicd/taskdef.json
      - sed -i -e "s#<ACCOUNT_ID>#$ACCOUNT_ID#" cicd/taskdef.json
      - sed -i -e "s#<DD_API_KEY>#$DD_API_KEY#" cicd/taskdef.json
      - sed -i -e "s#<LB_ENDPOINT>#$LB_ENDPOINT#" cicd/taskdef.json
      - sed -i -e "s#<DB_WRITE_ENDPOINT>#$DB_WRITE_ENDPOINT#" cicd/taskdef.json
      - sed -i -e "s#<DB_READ_ENDPOINT>#$DB_READ_ENDPOINT#" cicd/taskdef.json
      - cat cicd/appspec.yml
      - cat cicd/taskdef.json

artifacts:
  files:
    - imageDetail.json
    - cicd/appspec.yml
    - cicd/taskdef.json
